#!/usr/bin/env bash
set -euo pipefail

PORT="${INVOKE_PORT:-9090}"
HOST="${INVOKE_HOST:-0.0.0.0}"
WORKSPACE_ROOT="${WORKSPACE_ROOT:-/workspace}"
ROOT="${WORKSPACE_ROOT}/invokeai"

mkdir -p "$ROOT"

# Pick venv:
# - Prefer thin venv if present (Option A)
# - Fall back to core venv (Option B)
VENV="/opt/venvs/core"
if [ -x /opt/venvs/invoke/bin/python ]; then
  VENV="/opt/venvs/invoke"
fi

# Always run Invoke with an explicit root + config to avoid CLI flag drift
export INVOKEAI_ROOT="$ROOT"
export INVOKEAI_HOST="$HOST"
export INVOKEAI_PORT="$PORT"

CFG="$ROOT/config.yaml"
cat > "$CFG" <<EOF
# Autogenerated on container start
# Keeps host/port stable across InvokeAI versions.
# Root is still set via --root and/or INVOKEAI_ROOT.
host: ${HOST}
port: ${PORT}
EOF

# Activate selected venv
# shellcheck disable=SC1090
source "${VENV}/bin/activate"

# Some versions are "invokeai-web", others are "invokeai" with subcommands.
# We'll try the stable patterns first.

if command -v invokeai-web >/dev/null 2>&1; then
  # Newer builds often support --config
  if invokeai-web --help 2>&1 | grep -q -- '--config'; then
    exec invokeai-web --root "$ROOT" --config "$CFG"
  fi
  # Older builds: --root exists, host/port may come from config/env
  exec invokeai-web --root "$ROOT"
fi

if command -v invokeai >/dev/null 2>&1; then
  # Modern invokeai CLI usually has a "web" subcommand
  if invokeai --help 2>&1 | grep -qE '(^|[[:space:]])web($|[[:space:]])'; then
    # Some versions support --config on subcommands too
    if invokeai web --help 2>&1 | grep -q -- '--config'; then
      exec invokeai web --root "$ROOT" --config "$CFG"
    fi
    exec invokeai web --root "$ROOT"
  fi

  # Fallback: just run invokeai (might start the UI depending on version)
  exec invokeai
fi

echo "InvokeAI entrypoint not found in ${VENV}."
echo "--- Debug ---"
echo "VENV=${VENV}"
python -V || true
pip -V || true
pip list | sed -n '1,200p' || true
exit 1